Description: "Docker Repo"
AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  ProjectName:
    Type: String
  BranchName:
    Type: String

Resources:

  ECRRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Sub "${ProjectName}-${BranchName}"

  ServiceBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
  
  ServiceArtifactsBucket:
    Type: AWS::S3::Bucket
    Properties:
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  PreProcessGATagBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
  

Outputs:
  ServiceBucket:
    Description: Service Bucket
    Value: !Ref ServiceBucket

  ServiceArtifactsBucket:
    Description: Service artifacts bucket
    Value: !Ref ServiceArtifactsBucket
  
  PreProcessGATagBucket:
    Description: GA tag bucket
    Value: !Ref PreProcessGATagBucket